### ISSUE TITLE
Not working with some code

### ISSUE THREAD

**Issue by JDat** [Antosser/brainfuck-compiler-web#4]
From
```
var a
set a 1
```
to
```
var a
set a 11
```
not working.

> 14:29:36.159 Uncaught TypeError: c[0] is undefined
>     P https://brainfuck.antosser.xyz/assets/index.1af62a99.js:7
>     F https://brainfuck.antosser.xyz/assets/index.1af62a99.js:9
>     <anonymous> https://brainfuck.antosser.xyz/assets/index.1af62a99.js:9
>     jQuery 2
> index.1af62a99.js:7:988

Firefox v113.0.2

**Comment by Antosser** [comment]
Fixed 97d213b6957a10eab41de20f1841578fe6088cf4
